# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - update-online

build-linux-x64:
  only:
    - master
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  tags:
    - linux
  script:
    - echo "node `node -v`"
    - echo "npm `npm -v`"
    - yarn --registry=http://registry.npm.taobao.org
    - yarn test
    - yarn release --arch x64
    - cp bin/* /mnt/data/public/engine

# build-linux-arm64:
#   stage: build
#   tags:
#     - linux
#   script:
#     - docker run --rm --privileged multiarch/qemu-user-static:register --reset
#     - yarn --registry=http://registry.npm.taobao.org
#     - yarn test
#     - yarn release --arch arm64
#     - cp bin/* /mnt/data/public/engine

build-windows:
  only:
    - master
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  tags:
    - windows
  script:
    - node -v
    - npm -v
    - yarn --registry=http://registry.npm.taobao.org
    - yarn test
    - yarn release
    - cp bin\\* \\10.0.0.10\\data\\public\\engine

build-macos-x64:
  only:
    - master
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  tags:
    - macOS
  script:
    - echo "node `node -v`"
    - echo "npm `npm -v`"
    - yarn --registry=http://registry.npm.taobao.org
    - yarn test
    - yarn release --arch x64
    - cp bin/* /Volumes/data/public/engine

update:
  stage: update-online
  tags:
    - online
  script:
    - echo "node `node -v`"
    - echo "npm `npm -v`"
    - cd /root/client
    - git fetch && git reset --hard origin/$CI_COMMIT_REF_NAME
    - yarn --registry=http://registry.npm.taobao.org
    - yarn build
    - pm2 reload engine

